name: titanic-mlflow-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.7
  - pip
  - pip:
    - mlflow==2.19.0
    - pandas>=2.0.0
    - numpy>=1.24.0
    - scikit-learn>=1.3.0
    - matplotlib>=3.7.0
    - seaborn>=0.12.0
    - dagshub>=0.3.0
    - prometheus-client>=0.19.0
    - fastapi>=0.104.0
    - uvicorn>=0.24.0
